### ISSUE TITLE
Could you please update to latest version of cake

### ISSUE THREAD

**Issue by cbmdk** [RadioSystems/Cake.AzureStorage#20]
Hey, 
Getting 
Error: The assembly 'Cake.AzureStorage, Version=0.11.0.0, Culture=neutral, PublicKeyToken=null' 
is referencing an older version of Cake.Core (0.22.0). 
This assembly must reference at least Cake.Core version 0.26.0. 

could you please update to latest :)

**Comment by wharri220** [comment]
Merged PR #21 . Upgrade to Cake 0.32.1
